name: Test Project

on:
  push:
    branches:
      - main # Set the branch to main

jobs:
  test:
    runs-on: windows-latest
    steps:
      # Checkout code
      - name: Get code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: windows-latest
    needs: test # Ensure the 'test' job completes before 'deploy'
    steps:
      # Checkout code
      - name: Get code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Add deployment step (customize this as needed)
      - name: Deploy
        run: echo "Deployment steps go here"
